name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Case 01 [free]
      id: test-case-01-free
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 7
        setup-command: apt-get update && apt-get install -y curl && curl "https://gist.githubusercontent.com/johnghidiuflcc/0ab7ae00fa546871f5751d59b274b728/raw"
          -o test_01.py
    - name: Test Case 02 [immediate action required]
      id: test-case-02-immediate-action-required
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 7
        setup-command: apt-get update && apt-get install -y curl && curl "https://gist.githubusercontent.com/johnghidiuflcc/9604592ea201c02d582b61abc1a56294/raw"
          -o test_01.py
    - name: Test Case 03 [no joy]
      id: test-case-03-no-joy
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 7
        setup-command: apt-get update && apt-get install -y curl && curl "https://gist.githubusercontent.com/johnghidiuflcc/78ce6665bf5a4024f8dbb0ce18775b31/raw"
          -o test_01.py
    - name: Test Case 04 [password reset]
      id: test-case-04-password-reset
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 7
        setup-command: apt-get update && apt-get install -y curl && curl "https://gist.githubusercontent.com/johnghidiuflcc/bb846c4ffd541cd98db3da7d217ca0b7/raw"
          -o test_01.py
    - name: Test Case 05 [urgent]
      id: test-case-05-urgent
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 7
        setup-command: apt-get update && apt-get install -y curl && curl "https://gist.githubusercontent.com/johnghidiuflcc/18b8338a252534818c980b0d2089bf7b/raw"
          -o test_01.py
    - name: Test Case 06 [win]
      id: test-case-06-win
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 5
        setup-command: apt-get update && apt-get install -y curl && curl "https://gist.githubusercontent.com/johnghidiuflcc/cb611c317bbd0293f428213ed8acf4a3/raw"
          -o test_01.py
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-01-FREE_RESULTS: "${{steps.test-case-01-free.outputs.result}}"
        TEST-CASE-02-IMMEDIATE-ACTION-REQUIRED_RESULTS: "${{steps.test-case-02-immediate-action-required.outputs.result}}"
        TEST-CASE-03-NO-JOY_RESULTS: "${{steps.test-case-03-no-joy.outputs.result}}"
        TEST-CASE-04-PASSWORD-RESET_RESULTS: "${{steps.test-case-04-password-reset.outputs.result}}"
        TEST-CASE-05-URGENT_RESULTS: "${{steps.test-case-05-urgent.outputs.result}}"
        TEST-CASE-06-WIN_RESULTS: "${{steps.test-case-06-win.outputs.result}}"
      with:
        runners: test-case-01-free,test-case-02-immediate-action-required,test-case-03-no-joy,test-case-04-password-reset,test-case-05-urgent,test-case-06-win
